#!name=机场流量信息面板
#!desc=只需要填入链接。每个订阅可以通过使用大括号命名，例如 https://example.com/sub{我的订阅}
#!category=机场流量信息
#!arguments=订阅链接1:,订阅链接2:,订阅链接3:,订阅链接4:,订阅链接5:,订阅链接6:,订阅链接7:,订阅链接8:,订阅链接9:,订阅链接10:
#!arguments-desc=[参数设置]\n\n1. 只需要填入链接。每个订阅可以通过使用大括号命名，例如：https://abc.com/sub{订阅A}，面板会自动解析并命名为“订阅A”。\n2. 面板显示时只展示已填写的订阅，空项不会出现在面板中。\n3. 脚本会自动尝试 clash-verge-rev / clash-verge / mihomo 的请求方式提升兼容性。
# 更新日期：2026-03-08
# 版本：2.0.3

[Panel]
机场订阅=script-name=机场订阅,update-interval=3600

[Script]
机场订阅=type=generic,timeout=20,script-path=https://raw.githubusercontent.com/Roddy-D/test/main/traffic.js,script-update-interval=0,argument=url1={{{订阅链接1}}}&url2={{{订阅链接2}}}&url3={{{订阅链接3}}}&url4={{{订阅链接4}}}&url5={{{订阅链接5}}}&url6={{{订阅链接6}}}&url7={{{订阅链接7}}}&url8={{{订阅链接8}}}&url9={{{订阅链接9}}}&url10={{{订阅链接10}}}